### PR TITLE
Nodejs6 fix

### PR DESCRIPTION
**Pull request by leider**
## And now my proposal for a fix.

The underlying reason lies in the deep ends of node. They changed the default encoding for creating buffers internally inside the `crypto.js` from 'binary' to 'utf-8'. This is of course crap in the use case node-openid creates the Hmac.

Changing the Hmac creation to using a `buffer` fixes this as `crypto.js` only converts `strings` to buffers and leaves buffers untouched.

_happy patching_

And please also fix the legacy (1.0.x) version.

### CODE REVIEW

**Comment by leider** [comment]
Please wait with integrating this. I am currently not sure if it fixes the "real" issue in integration. :(

More to come...

**Comment by havard** [comment]
OK

**Comment by leider** [comment]
Guess I'm through now. - I'd be extremely pleased with a backport that is valid with this package.json: https://github.com/jaredhanson/passport-openid/blob/master/package.json

It has been a pleasure to work with you!

**Comment by leider** [comment]
Any plans for integrating it soon? - It is really urgent as it is a show stopper in our environment.

**Comment by havard** [comment]
Fixed in 2.0.4, backported to 1.0.1.

**Pull request closed without merging**
