### PR TITLE
Count handling for attribute exchange - safer implementation

### PR DESCRIPTION
**Pull request by vincentpeyrouse**
My apologies for the delay. I did a safer implementation with count value validation. (see #124 for history)

### CODE REVIEW

**Comment by havard** [comment]
Would make the (arbitrary) limit of 1000 a constant AX_MAX_COUNT or similar. Other than that, it's looking good to me. Can you add a commit extracting an AX_MAX_COUNT constant?

**Comment by GodezInc** [comment]
What about giving the opportunity to the user to override this value ?

**Comment by havard** [comment]
I can't imagine that it'll ever be useful in the real world, but if you'd like it to be an option to the AX extension, that's fine by me.

**Comment by GodezInc** [comment]
You may be right, in case where users want to reduce number of allowed values (for whatsoever validation or anything else) it would have much sense to do it in app logic.

**Comment by havard** [comment]
So, option it is then?

**Comment by havard** [comment]
Assuming the constant was preferred, closing this.

**Pull request merged**
