### PR TITLE
Fix: verifyAssertion times out on POST

### PR DESCRIPTION
**Pull request by Reregistered**
I received a POST from the server that was already complete. In that case verify the body as the events will never trigger.

node version: 0.10.33
express version: 3.20.1

### CODE REVIEW

**Comment by havard** [comment]
Thanks for the PR. Could you enlighten me on where the `request.complete` attribute comes from? I can't find it in the docs, and from what I can tell, trusting the `end` event should suffice?

**Comment by Reregistered** [comment]
Good question. I was testing with the everyauth sample which I assumed was generic enough. I haven't found the 'complete' flag documented, however it is part of the IncomingMessage class as seen here:

Node 0.12 - https://github.com/joyent/node/blob/master/lib/_http_incoming.js#L53-55
Node 0.10 - https://github.com/joyent/node/blob/v0.10.36/lib/http.js#L299-301
Node 0.8 - https://github.com/joyent/node/blob/v0.8.28/lib/http.js#L272-274

I investigated further and it looks like we miss the 'end' event when express' bodyParser middleware is in use, removing the middleware the code works as intended.

**Comment by havard** [comment]
Relying on undocumented (i.e. private) APIs is not a path I want to venture down. :)

It's really a bug in Express' bodyParser middleware or possibly the middleware pipeline in Express. Closing this, and recommending you contact them.

**Comment by jackquack** [comment]
It looks like this SO question brings light to this issue: http://stackoverflow.com/questions/18710225/node-js-get-raw-request-body-using-express

It seems like this bit of code here will not play nice if bodyParser is used as middleware before this code executes. The 'end' event will never fire here.

It seems that if ```req.body``` is present though (which _is_ documented), then bodyParser has run, and the property can be safely accessed.
Otherwise we're being called before bodyParser. In that case I don't know what to do. We can't hook in to listen to 'end' because the event will only be fired for one of the listeners...

**Pull request closed without merging**
