### PR TITLE
Added support for honoring NO_PROXY list

### PR DESCRIPTION
**Pull request by sreuter**

### CODE REVIEW

**Comment by sreuter** [comment]
@havard Can you look into this anytime soon? I'd like to get this pulled and released to open the PR for passport-openid.

**Comment by havard** [comment]
I second @jtblin in looking at request.

**Comment by sreuter** [comment]
Totally agree. So maybe it even makes sense to actually use request here?

**Comment by havard** [comment]
I assume that by 'here' you mean 'in this library'. Yes, I second that. It would remove handling (at least) proxies, redirects, some serialization, perhaps even more, from node-openid. I am all for it. :)

**Comment by havard** [comment]
Did you land on anything?

**Comment by jtblin** [comment]
Nope, sorry I had a look but that would touch (remove) a lot of code and I didn't have the bandwidth personally.

**Comment by sreuter** [comment]
~~Christman~~ ShipIT came early this year ;) This is now superseded by #135, which uses request to do the http requests.

**Pull request closed without merging**
